### <div> <b> NUMPY EXERCISE </b> </div>

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an empty array of 20 0's and replace the 4th object with the number 5

In [5]:
a = np.zeros(20)
a[3] = 5
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named array_copy

In [6]:
array_master = np.ones(20)
array_copy = array_master.copy()
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

#### Create an array of the integers from 10 to 50

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array containing 30 1's and broadcast all the one's to the value 100

In [8]:
a = np.ones(30)
a = a*100
a

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

<div> Create an array of integers starting from 21 until 31 and name it as array1 </div>
<div> Create an array of integers starting from 11 until 21 and name it array2   </div>
<div> Calculate the difference between array1 and array2 </div>

In [10]:
array1 = np.arange(21,32)
array2 = np.arange(11, 22)
array1 - array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

<div> Create an array of all even integers from 2 to 10 and name it a1  </div>
<div> Create an array of all even integers from 22 to 30 and name it a2  </div>
<div> a) Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ]  </div>
<div>  b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]  </div>

In [11]:
a1 = np.arange(2,11,2)
a2 = np.arange(22,31,2)
#a:
a = np.stack((a1, a2))
print(a, '\n')

#b:
b = np.column_stack((a1, a2))
print(b)

[[ 2  4  6  8 10]
 [22 24 26 28 30]] 

[[ 2 22]
 [ 4 24]
 [ 6 26]
 [ 8 28]
 [10 30]]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [14]:
np.random.rand(1)

array([0.05263124])

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

#### Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [15]:
a = np.random.rand(1,10)
a > 0.2

array([[False,  True,  True,  True,  True, False,  True,  True,  True,
         True]])

#### Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [16]:
a = np.eye(10)
a[a == 0] = 21
a

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
np.random.randn(25)

array([-1.19724256,  0.79801404,  1.96885235, -1.13352025,  0.75731803,
       -1.2355245 , -0.95156175,  0.05487616,  0.79106468, -1.48579342,
       -0.13165973,  0.71545538, -0.41987772, -1.33848951,  0.0578073 ,
        1.60285318, -1.68113396, -1.0787032 , -1.21915206,  0.4465577 ,
        0.95289814, -1.06334881,  0.03158585, -1.22413899, -0.18297428])

#### Create the following matrix:

In [18]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [19]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [20]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [22]:
a = np.arange(1,26).reshape(5,5)
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [23]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [24]:
a[3,4]

20

In [25]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [26]:
a[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [27]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [28]:
a[-1, :]  # OR a[-1]

array([21, 22, 23, 24, 25])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
a[3:,:]  # OR a[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in the array 'a' above

In [31]:
a.sum()

325

#### Get the standard deviation of the values in mat

In [32]:
a.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [33]:
a.sum(axis = 0)

array([55, 60, 65, 70, 75])

#### d) Calculate the mean of all values in the matrix

In [34]:
a.mean()

13.0

#### e) Retrieve the largest number from the matrix

In [35]:
a.max()

25

#### e) Retrieve the smallest number from the matrix

In [36]:
a.min()

1