## Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## initially Lets import numpy
import numpy as np

In [2]:
my_lst = [1, 2, 3, 4, 5]

arr = np.array(my_lst)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
## Multinested array
my_lst1 = [1, 2, 3, 4, 5]
my_lst2 = [2, 3, 4, 5, 6]
my_lst3 = [9, 7, 6, 8, 9]

arr1 = np.array([my_lst1,my_lst2,my_lst3])

In [6]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
## check the shape of the array
arr1.shape

(3, 5)

### Indexing 

In [9]:
## Accessing the array elements
arr

array([1, 2, 3, 4, 5])

In [10]:
arr[3]

4

In [11]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [12]:
arr1[1:, :2]

array([[2, 3],
       [9, 7]])

In [13]:
arr1[:, 3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
arr[3:] = 100

In [16]:
arr

array([  1,   2,   3, 100, 100])

In [17]:
# Some conditions very useful in Exploratory Data Analysis, EDA 
val = 1
arr[arr < 3]

array([1, 2])

In [18]:
# Create arrays and reshape

np.arange(0, 8).reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
arr1 = np.arange(0, 10).reshape(2, 5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
arr2 = np.arange(0,10).reshape(2, 5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
arr1 * arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [22]:
np.ones((2, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# random distribution
np.random.rand(4, 4)

array([[0.73605956, 0.70199109, 0.42358265, 0.85683739],
       [0.59760602, 0.22784217, 0.19628494, 0.51067853],
       [0.34600516, 0.86655464, 0.79040284, 0.4921198 ],
       [0.50944876, 0.02921425, 0.91987496, 0.8091695 ]])

In [24]:
arr3 = np.random.randn(5, 5)

In [25]:
arr3

array([[-0.30674723, -2.32743301, -0.74481766, -0.46569194, -0.35972939],
       [-0.42598241, -0.88012675,  1.79499179,  1.0554744 , -0.13077523],
       [ 1.65649126, -0.81737424,  2.59121323, -1.34387214,  1.11595919],
       [ 0.06543289, -0.36482899,  2.61794068,  0.74126507,  0.30379286],
       [-1.07457186,  1.78383756,  0.344077  , -1.6866504 ,  0.77472487]])

In [26]:
np.random.randint(0, 100, 5).reshape(5, 1)

array([[68],
       [50],
       [19],
       [83],
       [69]])

In [27]:
np.random.random_sample((1, 5))

array([[0.18691523, 0.64932759, 0.80834761, 0.91428936, 0.87798601]])